# freebsd_instance:
#   image_family: freebsd-13-2
#
# freebsd_task:
#   install_script: . ./ci/cirrus/cirrus-install-freebsd.sh
#   script: mkdir test_dir && cd test_dir && echo $PWD && python3.9 -c "import randomgen; randomgen.test([])"

arm_container:
  image: python:slim

arm_task:
  install_script: . ./ci/cirrus/cirrus-install-arm.sh
  script: mkdir test_dir && cd test_dir && echo $PWD && python3 -c "import randomgen; randomgen.test([])"
