freebsd_instance:
  image_family: freebsd-13-2

task:
  install_script: . ./ci/cirrus-install.sh
  script: mkdir test_dir && cd test_dir && echo $PWD && python3.9 -c "import randomgen; randomgen.test([])"


