---
kind: pipeline
type: docker
name: test-on-arm64

platform:
  os: linux
  arch: arm64


steps:
- name: test
  image: ubuntu:latest
  commands:
    - uname -a
    - apt-get update
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get install libatlas-base-dev build-essential cython3 python3-numpy python3 python3-dev python3-pip libxml2-dev libxslt-dev python3-lxml -y
    - gcc tools/long_double_sizes.c -o long_double_sizes && ./long_double_sizes
    - pip3 install -r requirements.txt --upgrade
    - pip3 install -r requirements-dev.txt
    - pip3 install -e . --no-build-isolation
    - pytest -r a randomgen
