# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#passing-parameters
schedules:
- cron: "27 3 * * 0"
  # 3:27am UTC every Sunday
  displayName: Weekly build
  branches:
    include:
    - main
  always: true

trigger:
- main


variables:
  MKL_NUM_THREADS: 1
  NUMEXPR_NUM_THREADS: 1
  OMP_NUM_THREADS: 1
  VML_NUM_THREADS: 1
  OPENBLAS_NUM_THREADS: 1
  JUPYTER_PLATFORM_DIRS: 1
  PYTHONHASHSEED: 12345678 # Ensure tests are correctly gathered by xdist
  TEST_INSTALL: false
  MPLBACKEND: agg
  test.install: false
  pip.pre: false
  BUILD_FLAGS: ''
  coverage: true

jobs:
- template: ci/azure/azure_template_posix.yml
  parameters:
    name: macOS
    vmImage: macOS-latest
    
- template: ci/azure/azure_template_posix.yml
  parameters:
    name: Linux
    vmImage: ubuntu-latest

- template: ci/azure/azure_template_windows.yml
  parameters:
    name: Windows
    vmImage: windows-latest
