# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

parameters:
  # defaults for any parameters that are not specified
  name: ''
  vmImage: ''


jobs:

- job: ${{ parameters.name }}Test
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      python39_win_latest:
        python.version: '3.9'
      python310_win_latest:
        python.version: '3.10'
      python311_win_latest:
        python.version: '3.11'
      python312_win_latest:
        python.version: '3.12'
      python313_win_latest:
        python.version: '3.13'
      python3124win_latest:
        python.version: '3.14'
    maxParallel: 10

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'
    displayName: 'Use Python $(python.version)'

  - script: |
      python -m pip install --upgrade pip wheel -U
      python -m pip install -r requirements.txt -U
      python -m pip install -r requirements-dev.txt  -U
    displayName: 'Install dependencies'

  - script: |
      python -m pip list
    displayName: 'List Configuration'

  - script: |
      python -m pip install -e . -v --no-build-isolation
    displayName: 'Build Cython Extensions'

  - script: |
      pytest --junitxml=junit/test-results.xml --durations=25 -v --cov=randomgen --cov-branch --cov-report xml:coverage.xml --cov-report term randomgen
    displayName: 'pytest'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/test-results.xml'
      testRunTitle: 'Python $(python.version)'
    condition: succeededOrFailed()

  - pwsh: |
      Invoke-WebRequest https://uploader.codecov.io/latest/windows/codecov.exe -OutFile codecov.exe
      ./codecov -f coverage.xml -F adder -F subtractor
    displayName: 'Codecov upload'
