from typing import Dict, Optional, Union

from randomgen.common import BitGenerator
from randomgen.typing import IntegerSequenceSeed, SeedMode

class PCG32(BitGenerator):
    def __init__(
        self,
        seed: Optional[IntegerSequenceSeed] = ...,
        inc: int = ...,
        *,
        mode: Optional[SeedMode] = ...
    ) -> None: ...
    def seed(
        self, seed: Optional[IntegerSequenceSeed] = ..., inc: int = ...
    ) -> None: ...
    @property
    def state(self) -> Dict[str, Union[str, Dict[str, int]]]: ...
    @state.setter
    def state(self, value: Dict[str, Union[str, Dict[str, int]]]) -> None: ...
    def advance(self, delta: int) -> None: ...
    def jump(self, iter: int = ...) -> PCG32: ...
    def jumped(self, iter: int = ...) -> PCG32: ...
