name: Build wheels

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '37 0 * * 2' # 2/weekly

jobs:
  build_wheels:
    name: ${{ matrix.os }}, Python ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        python: [cp312]
        os: [ubuntu-latest, windows-latest, macos-latest, macos-13]
    env:
      BUILD_COMMIT: "main"
      CIBW_BUILD: ${{ matrix.python }}-*
      CIBW_ARCHS_LINUX: "x86_64"
      CIBW_ARCHS_MACOS: "auto"
      CIBW_SKIP: "pp* *-musllinux_* *-win32"
      CIBW_TEST_REQUIRES: pytest pytest-xdist
      CIBW_TEST_COMMAND: python -c "import randomgen; randomgen.test(['--skip-slow','-n','2'])"
      CIBW_REPAIR_WHEEL_COMMAND_LINUX: 'auditwheel repair --strip -w {dest_dir} {wheel}'
      MKL_NUM_THREADS: 1
      OMP_NUM_THREADS: 1
      OPENLAS_NUM_THREADS: 1

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.21
        with:
          output-dir: wheelhouse
